import { Ramaraja } from "next/font/google";
import "./globals.css";

const ramaraja = Ramaraja({ 
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ramaraja.className}>{children}</body>
    </html>
  );
}
